### ISSUE TITLE
OpenHAB2: Habmin JS error: URIError: malformed URI sequence

### ISSUE THREAD

**Issue by grzech1983** [cdjackson/HABmin2#24]
Hello,

I'm getting JS error in latest build which makes habmin not working at all:

URIError: malformed URI sequence app.js:57:17

which points to:

        'fr-FR': decodeURIComponent(escape("FranĂ§ais (France)"))

from

    .value('localeSupported', {
        'en-GB': "English (United Kingdom)",
        'de-DE': "Deutsch (Deutschland)",
        'fr-FR': decodeURIComponent(escape("FranĂ§ais (France)"))
    })

Regards

**Comment by cdjackson** [comment]
This is already fixed. Please use the latest snapshot build in the output folder.

**Comment by grzech1983** [comment]
Are you sure that this has been fixed? I see that jar file has been changed 14 days ago and I've downloaded this file today.

**Comment by cdjackson** [comment]
Yes - it’s fixed (see https://github.com/cdjackson/HABmin2/issues/23 <https://github.com/cdjackson/HABmin2/issues/23>).  However, the error isn’t in the JAR - or are you using OH2 - in which case it is in the JAR, and no it’s not fixed…  I have a problem compiling the OH2 JAR at the moment as I’ve exported it out of the OH folder as it won’t be merged into the OH repo. I can run it in the debugger, but am still trying to work out how to compile it standalone…

So - fixed in OH1 only.

**Comment by grzech1983** [comment]
Ah. Ok. I was testing OH2 and thats where I've got this error.

**Comment by cdjackson** [comment]
Ok - then sorry - for the minute I can’t fix this :(  I’ll try and take another look at it today...

**Comment by grzech1983** [comment]
This is not a big issue. I just wanted to check OH2 if it works correctly with Android app and I also checked habmin which was not working and that's why I've sent this issue report. Take your time there is no hurry here.

**Comment by cdjackson** [comment]
Ok - thanks. It’s a bigger issue for me though as I’m trying to move all my stuff towards OH2 ;)

When I get this sorted I’ll post back here - it might take some time though as I spent quite a bit of time trying to solve this already...

**Comment by cdjackson** [comment]
I've updated the snapshots in the [output folder](https://github.com/cdjackson/HABmin2/tree/master/output). This should now be fixed for the OH2 JAR as well...

**Comment by grzech1983** [comment]
It works. Thanks

**Comment by grzech1983** [comment]
One more thing: should I see z-wave configuration section under Configuration menu?

**Comment by cdjackson** [comment]
No - at the moment in OH2 zwave interface isn’t supported. This is something I’ve been trying to add - I’ve been trying to avoid requiring the zwave binding in order to run HABmin, but this seems to not be possible… Hopefully I’ll get this interface added shortly, although I’d also hoped to port the zwave binding over to OH2 natively. This is working, but as I’m missing some functionality in ESH I’m currently stalled on that one...

**Comment by grzech1983** [comment]
Ok. Thanks. Should I open another issue with z-wave support in OH2?

**Comment by cdjackson** [comment]
Yes - feel free to add an issue for this.

**Comment by grzech1983** [comment]
Done
